#!/usr/bin/env python

import re
import sys
import datetime

POST_PATTERN = re.compile(r'(^\s*postDate:\s*)([\s\S]*)([\r\n])')
UPDATE_PATTERN = re.compile(r'(^\s*updateDate:\s*)([\s\S]*)([\r\n])')

def main():
    if len(sys.argv) < 2:
        print('Too few arguments!')
        exit(1)

    path = sys.argv[1]

    lines = get_lines(path)

    if not has_post_date(lines):
        add_post_date(lines)
    else:
        add_update_date(lines)

    write_front_matter(path, lines)

def get_lines(path: str):
    with open(path, mode='r') as f:
        l = f.readlines()
    return l

def write_front_matter(path: str, new_lines: list[str]):
    with open(path, mode='w') as f:
        f.writelines(new_lines)

def has_post_date(lines: list[str]):
    fm = front_matter(lines)
    for i, line in fm:
        m = POST_PATTERN.match(line)
        if m:
            return m.group(2) != 'null'
    return False

def add_post_date(lines: list[str]):
    add_date(POST_PATTERN, lines)

def add_update_date(lines: list[str]):
    add_date(UPDATE_PATTERN, lines)

def add_date(pat: re.Pattern[str], lines: list[str]):
    now = datetime.datetime.now()
    def format(m: re.Match[str]):
        return f'{m.group(1)}\'{now.isoformat()}\'{m.group(3)}'

    fm = front_matter(lines)
    for i, line in fm:
        if pat.match(line):
            lines[i] = pat.sub(format, line)
            break

# generator
def front_matter(lines: list[str]):
    pat = re.compile(r'^---*[\r\n]')
    dash_count = 0
    for i, line in enumerate(lines):
        if dash_count >= 2:
            break
        if pat.match(line):
            dash_count += 1
            continue
        yield (i, line)

if __name__ == '__main__':
    main()