#!/bin/zsh

BLOG_DIR=$(cd $(dirname $(readlink -f $0)); cd ..; pwd)
SCRIPT_DIR=$BLOG_DIR/scripts
TARGET_MD=$BLOG_DIR/_posts/$1

# 投稿日付 or 更新日付を記入; attach-date requires full path
$SCRIPT_DIR/attach-date $TARGET_MD

# 画像のファイル名を変更; protect-photo requires full path
# Exif情報を削除
$SCRIPT_DIR/protect-photo $TARGET_MD

# commit & push
git add $BLOG_DIR/. && git commit -m 'post/update '$1 && git push origin main