#!/bin/zsh -e

if [ $# -lt 1 ]; then
  echo "Usage: "$0" [slug-name]"
  exit 1
fi

BLOG_DIR=$(cd $(dirname $(readlink -f $0)); cd ..; pwd)
SCRIPT_DIR=$BLOG_DIR/scripts
TARGET_MD=$BLOG_DIR/_posts/$1.md

# 投稿日付 or 更新日付を記入; attach-date requires full path
echo 'Attach date'
$SCRIPT_DIR/attach-date $TARGET_MD

# 画像のファイル名を変更; protect-photo requires full path
# Exif情報を削除
echo 'Remove Exif info'
$SCRIPT_DIR/protect-photo $TARGET_MD

# commit & push
echo 'Uploading'
git add $BLOG_DIR/. && git commit -m 'post/update '$1 && git push origin main