#!/bin/zsh

SCRIPT=$(cd $(dirname $(readlink -f $0)); cd ..; pwd)

# 投稿日付 or 更新日付を記入
$SCRIPT/scripts/attach-date $SCRIPT/_posts/$1
# 画像のファイル名を変更
# blog/_posts/にmarkdownを移動
# blog/public/assets/blog/***/に画像ファイルを移動
# commit & push
# git add $SCRIPT/. && git commit -m 'post/update '$1 && git push origin main
git add $SCRIPT/. && git commit -m 'post/update '$1 && git push origin main
# echo 'git add '$SCRIPT/.
# echo 'git commit -m "post/update $1"'
# echo 'git push origin main'