#!/usr/bin/env python

import os
import sys
import re
import uuid
from PIL import Image

ORIGINAL_TO_RANDOM = {}
BLOG_DIR = ''
ASSETS_DIR = '/assets/blog'
# ![***](/assets/blog/***/***.jpg)
# ^^^^^^^^^^^^^^^^^^/^^^^^^^^^^^/^
#     group 1         group 2    group 3
IMAGE_PATTERN = re.compile(r'(!\[[^\]]*\]\(' + ASSETS_DIR + r')([^\)]*)(\))')

def main():
    global BLOG_DIR
    if len(sys.argv) < 2:
        print('Too few arguments!')
        exit(1)

    md_path = sys.argv[1]
    BLOG_DIR = find_blog_dir(md_path)

    image_pathes = search_images(md_path)
    # print(image_pathes)

    for image_path in image_pathes:
        # rename_image(image_path)
        remove_exif(image_path)

    # replace_image_pathes(md_path)

def find_blog_dir(md_path: str):
    i = md_path.rfind('/_posts')
    return md_path[:i]

def search_images(image_path: str):
    images = []
    with open(image_path, mode='r') as f:
        text = f.read()
        for m in IMAGE_PATTERN.finditer(text, re.MULTILINE):
            images.append(BLOG_DIR + '/public' + ASSETS_DIR + m.group(2))
    return images

def rename_image(image_path: str):
    new_path = random_filename(image_path)
    os.rename(image_path, new_path)

def remove_exif(image_path: str):
    with Image.open(image_path) as image:
        # next 3 lines strip exif
        image_data = list(image.getdata())
        image_without_exif = Image.new(image.mode, image.size)
        image_without_exif.putdata(image_data)

        image_without_exif.save(image_path)

def random_filename(image_path: str):
    i = image_path.rfind('/') + 1
    path = image_path[:i]
    i = image_path.rfind('.')
    ext = image_path[i:]
    new = path + str(uuid.uuid4()) + ext
    ORIGINAL_TO_RANDOM[image_path] = new
    return new

if __name__ == '__main__':
    main()